config/routes.rb
Rails.application.routes.draw do
  resources :empresa_choferes do
    get :search, on: :collection
  end
  resources :matriculas do
    get :search, on: :collection
  end
  resources :choferes
  resources :empresas
  resources :vehiculos
  resources :matriculas_log
  resources :tarifas
  resources :liquidacion_de_viajes do
    get :last, on: :collection
  end

  root to: 'liquidacion_de_viajes#index'
end

app/models/tarifa.rb
class Tarifa < ActiveRecord::Base
  self.table_name = 'tarifas'
  self.inheritance_column = 'ruby_type'
  self.primary_key = 'id'

  if ActiveRecord::VERSION::STRING < '4.0.0' || defined?(ProtectedAttributes)
    attr_accessible :fecha, :valor_ba_diu, :valor_ba_noc, :valor_fi_diu, :valor_fi_noc
  end  

  def self.get_valor_bandera_diurna
    tmp = Tarifa.order('fecha DESC').limit(1)
    return tmp[0].valor_ba_diu
  end

  def self.get_valor_bandera_nocturna
    tmp = Tarifa.order('fecha DESC').limit(1)
    return tmp[0].valor_ba_noc
  end
  
  def self.get_valor_ficha_diurna
    tmp = Tarifa.order('fecha DESC').limit(1)
    return tmp[0].valor_fi_diu
  end

  def self.get_valor_ficha_nocturna
    tmp = Tarifa.order('fecha DESC').limit(1)
    return tmp[0].valor_fi_noc
  end

end

app/controllers/tarifas_controller.rb
class TarifasController < ApplicationController
  before_action :set_tarifa, only: [:show, :edit, :update, :destroy]

  # GET /tarifas
  # GET /tarifas.json
  def index
    @tarifas = Tarifa.all
  end

  # GET /tarifas/1
  # GET /tarifas/1.json
  def show
  end

  # GET /tarifas/new
  def new
    @tarifa = Tarifa.new
  end

  # GET /tarifas/1/edit
  def edit
  end

  # POST /tarifas
  # POST /tarifas.json
  def create
    @tarifa = Tarifa.new(tarifa_params)

    respond_to do |format|
      if @tarifa.save
        format.html { redirect_to @tarifa, notice: 'Tarifa was successfully created.' }
        format.json { render :show, status: :created, location: @tarifa }
      else
        format.html { render :new }
        format.json { render json: @tarifa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tarifas/1
  # PATCH/PUT /tarifas/1.json
  def update
    respond_to do |format|
      if @tarifa.update(tarifa_params)
        format.html { redirect_to @tarifa, notice: 'Tarifa was successfully updated.' }
        format.json { render :show, status: :ok, location: @tarifa }
      else
        format.html { render :edit }
        format.json { render json: @tarifa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tarifas/1
  # DELETE /tarifas/1.json
  def destroy
    @tarifa.destroy
    respond_to do |format|
      format.html { redirect_to tarifas_url, notice: 'Tarifa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarifa
      @tarifa = Tarifa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tarifa_params
      params.require(:tarifa).permit(:fecha, :valor_ba_diu, :valor_ba_noc, :valor_fi_diu, :valor_fi_noc)
    end
end

app/views/tarifas/_form.html.erb
<%= form_for(@tarifa, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @tarifa.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@tarifa.errors.count, "error") %> prohibited this tarifa from being saved:</h4>

      <ul>
      <% @tarifa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :fecha, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :fecha, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :valor_ba_diu, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :valor_ba_diu, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :valor_ba_noc, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :valor_ba_noc, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :valor_fi_diu, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :valor_fi_diu, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :valor_fi_noc, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :valor_fi_noc, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/tarifas/edit.html.erb
<div class="page-header">
  <%= link_to tarifas_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Atras
  <% end %>
 
  <h1>Editar tarifa</h1>
</div>

<%= render 'form' %>

app/views/tarifas/index.html.erb
<div class="page-header">
  <%= link_to new_tarifa_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Nueva Tarifa
  <% end %>
  <h3>Tarifas</h3>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Fecha</th>
        <th>Bandera diurna</th>
        <th>Bandera nocturna</th>
        <th>Ficha diurna</th>
        <th>Ficha nocturna</th>       
        <th></th>       
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @tarifas) do |tarifa| %>
        <td><%= tarifa.fecha.strftime("%d/%m/%Y") %></td>
        
        <td><div align="right"><%= number_with_precision(tarifa.valor_ba_diu, 
          :precision => 2, :delimiter => ".", :separator => ",") %></td>  
        
        <td><div align="right"><%= number_with_precision(tarifa.valor_ba_noc, 
          :precision => 2, :delimiter => ".", :separator => ",") %></td>  
        
        <td><div align="right"><%= number_with_precision(tarifa.valor_fi_diu, 
          :precision => 2, :delimiter => ".", :separator => ",") %></td>  
     
        <td><div align="right"><%= number_with_precision(tarifa.valor_fi_noc, 
          :precision => 2, :delimiter => ".", :separator => ",") %></td>        
        <td><%= link_to 'Editar', edit_tarifa_path(tarifa) %></td>       
      <% end %>
    </tbody>
  </table>
</div>

app/views/tarifas/new.html.erb
<div class="page-header">
  <%= link_to tarifas_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Atras
  <% end %>
  <h1>Agregar tarifa</h1>
</div>

<%= render 'form' %>

app/views/tarifas/show.html.erb
<div class="page-header">
  <%= link_to tarifas_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Atras
  <% end %>
  <%= link_to edit_tarifa_path(@tarifa), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Tarifa</h1>
</div>

<dl class="dl-horizontal">
  <dt>Fecha:</dt>
  <dd><%= @tarifa.fecha.strftime("%d/%m/%Y") %></dd>

  <dt>Bandera diurna:</dt>
  <dd><%= @tarifa.valor_ba_diu %></dd>

  <dt>Bandera nocturna:</dt>
  <dd><%= @tarifa.valor_ba_noc %></dd>

  <dt>Ficha diurna:</dt>
  <dd><%= @tarifa.valor_fi_diu %></dd>

  <dt>Ficha nocturna:</dt>
  <dd><%= @tarifa.valor_fi_noc %></dd>

</dl>