config/routes.rb
Rails.application.routes.draw do
  resources :empresa_choferes do
    get :search, on: :collection
  end
  resources :matriculas do
    get :search, on: :collection
  end
  resources :choferes
  resources :empresas
  resources :vehiculos
  resources :matriculas_log
  resources :tarifas
  resources :liquidacion_de_viajes do
    get :last, on: :collection
  end

  root to: 'liquidacion_de_viajes#index'
end

app/controllers/choferes_controller.rb
class ChoferesController < ApplicationController
  before_action :set_chofer, only: [:show, :edit, :update, :destroy]

  # GET /choferes
  # GET /choferes.json
  def index
    if params[:estado]      
      @estado = params[:estado].to_i       
      @choferes = Chofer.all.order("apellidos ASC")
    end   
  end

  # GET /choferes/1
  # GET /choferes/1.json
  def show
  end

  # GET /choferes/new
  def new
    @chofer = Chofer.new
  end

  # GET /choferes/1/edit
  def edit
  end

  # POST /choferes
  # POST /choferes.json
  def create
    @chofer = Chofer.new(chofer_params)

    respond_to do |format|
      if @chofer.save
        format.html { redirect_to @chofer, notice: 'Se ha creado el registro del chofer.' }
        format.json { render :show, status: :created, location: @chofer }
      else
        format.html { render :new }
        format.json { render json: @chofer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /choferes/1
  # PATCH/PUT /choferes/1.json
  def update
    respond_to do |format|
      if @chofer.update(chofer_params)
        format.html { redirect_to @chofer, notice: 'Actualizacion realizada.' }
        format.json { render :show, status: :ok, location: @chofer }
      else
        format.html { render :edit }
        format.json { render json: @chofer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choferes/1
  # DELETE /choferes/1.json
  def destroy
    @chofer.destroy
    respond_to do |format|
      format.html { redirect_to choferes_url, notice: 'Chofer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chofer
      @chofer = Chofer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chofer_params
      params.require(:chofer).permit(:nombres, :apellidos, :apodo, :ci_numero, :ci_vencim, :lc_numero, :lc_vencim, :cs_numero, :cs_vencim, :fe_nacim, :direccion, :tel_domic, :tel_celular, :tel_contacto, :mutualista, :emergencia, :observ, :is_activo)
    end
end

app/views/choferes/_form.html.erb
<%= form_for(@chofer, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @chofer.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@chofer.errors.count, "error") %> prohibited this chofer from being saved:</h4>

      <ul>
      <% @chofer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombres, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nombres, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :apellidos, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :apellidos, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :apodo, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :apodo, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ci_numero, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :ci_numero, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ci_vencim, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :ci_vencim, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :lc_numero, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :lc_numero, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :lc_vencim, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :lc_vencim, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cs_numero, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :cs_numero, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cs_vencim, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :cs_vencim, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fe_nacim, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :fe_nacim, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :direccion, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :direccion, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tel_domic, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :tel_domic, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tel_celular, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :tel_celular, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tel_contacto, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :tel_contacto, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :mutualista, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :mutualista, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :emergencia, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :emergencia, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :observ, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :observ, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :is_activo, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :is_activo, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Confirmar", :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/choferes/edit.html.erb
<div class="page-header">
  <%= link_to choferes_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Atras
  <% end %>
  <%= link_to @chofer, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Visualizar
  <% end %>
  <h1>Edicion de chofer</h1>
</div>

<%= render 'form' %>

app/views/choferes/index.html.erb
<div class="page-header">
  <%= link_to new_chofer_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Agregar Chofer
  <% end %>
  <h1>Choferes</h1>
</div>

<%= form_tag choferes_path, :method => 'get', id: "search-form" do %>
 <div class="field"> 

 <%= label_tag "Estado:  " %>  
 <%= select_tag(:estado, options_for_select([
  ['Activos', 1], ['Inactivos', 2] 
  ], selected: @estado )) %> 

  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   

  <%= submit_tag "Aplicar seleccion" %>
  <br><br>
</div>
<% end %>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Nombres</th>
        <th>Apellidos</th>           
        <th>Cedula</th>           
        <th>Libreta chofer</th>
        <th>Apodo</th>            
        <th>Telefono</th>
        <th>Celular</th>                 
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @choferes) do |chofer| %>
        <td><%= chofer.nombres %></td>
        <td><%= chofer.apellidos %></td>           
        <td><%= chofer.ci_numero %></td>           
        <td><%= chofer.lc_numero %></td>
        <td><%= chofer.apodo %></td>
        <td><%= chofer.tel_domic %></td>
        <td><%= chofer.tel_celular %></td>       
          
        <td><%= link_to 'Ver', chofer %></td>
        <td><%= link_to 'Editar', edit_chofer_path(chofer) %></td>        
      <% end %>
    </tbody>
  </table>
</div>

app/views/choferes/new.html.erb
<div class="page-header">
  <%= link_to choferes_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Atras
  <% end %>
  <h1>Nuevo chofer</h1>
</div>

<%= render 'form' %>

app/views/choferes/show.html.erb
<div class="page-header">
  <%= link_to choferes_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Atras
  <% end %>
  <%= link_to edit_chofer_path(@chofer), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Chofer</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nombres:</dt>
  <dd><%= @chofer.nombres %></dd>

  <dt>Apellidos:</dt>
  <dd><%= @chofer.apellidos %></dd>

  <dt>Apodo:</dt>
  <dd><%= @chofer.apodo %></dd>

  <dt>Ci numero:</dt>
  <dd><%= @chofer.ci_numero %></dd>

  <dt>Ci vencim:</dt>
  <dd><%= @chofer.ci_vencim %></dd>

  <dt>Lc numero:</dt>
  <dd><%= @chofer.lc_numero %></dd>

  <dt>Lc vencim:</dt>
  <dd><%= @chofer.lc_vencim %></dd>

  <dt>Cs numero:</dt>
  <dd><%= @chofer.cs_numero %></dd>

  <dt>Cs vencim:</dt>
  <dd><%= @chofer.cs_vencim %></dd>

  <dt>Fe nacim:</dt>
  <dd><%= @chofer.fe_nacim %></dd>

  <dt>Direccion:</dt>
  <dd><%= @chofer.direccion %></dd>

  <dt>Tel domic:</dt>
  <dd><%= @chofer.tel_domic %></dd>

  <dt>Tel celular:</dt>
  <dd><%= @chofer.tel_celular %></dd>

  <dt>Tel contacto:</dt>
  <dd><%= @chofer.tel_contacto %></dd>

  <dt>Mutualista:</dt>
  <dd><%= @chofer.mutualista %></dd>

  <dt>Emergencia:</dt>
  <dd><%= @chofer.emergencia %></dd>

  <dt>Observ:</dt>
  <dd><%= @chofer.observ %></dd>

  <dt>Is activo:</dt>
  <dd><%= @chofer.is_activo %></dd>

</dl>