config/routes.rb
Rails.application.routes.draw do
  resources :empresa_choferes do
    get :search, on: :collection
  end
  resources :matriculas do
    get :search, on: :collection
  end
  resources :choferes
  resources :empresas
  resources :vehiculos
  resources :matriculas_log
  resources :tarifas
  resources :liquidacion_de_viajes do
    get :last, on: :collection
  end

  root to: 'liquidacion_de_viajes#index'
end

app/models/matricula.rb
class Matricula < ActiveRecord::Base
  self.table_name = 'matriculas'
  self.inheritance_column = 'ruby_type'
  self.primary_key = 'id'

  if ActiveRecord::VERSION::STRING < '4.0.0' || defined?(ProtectedAttributes)
    attr_accessible :codigo, :empresa_id
  end

  belongs_to :empresa, :foreign_key => 'empresa_id', :class_name => 'Empresa'
  has_many :matriculas_log, :foreign_key => 'matricula_id', :class_name => 'MatriculasLog'
  has_many :empresas, :through => :matriculas_log, :foreign_key => 'empresa_id', :class_name => 'Empresa'
  has_many :vehiculos, :through => :matriculas_log, :foreign_key => 'vehiculo_id', :class_name => 'Vehiculo'

  def get_nombre_empresa
  	begin
  	  empresa = Empresa.find(self.empresa_id)
  	  return empresa.razon_social
  	rescue Exception => e
  	  return ""
  	end
  end

  def get_vehiculo
    operaciones = MatriculaLog.where("matricula_id = ?", self.id).order('fecha DESC').limit(1)
    vehiculo = Vehiculo.find(operaciones[0].vehiculo_id)

    #return Vehiculo.find(80)
  end

  def self.search1(search)
    where("codigo = ?", search)
  end

  def as_json(options = {})
    super(options.merge(include: :empresa))
  end

end

app/controllers/matriculas_controller.rb
class MatriculasController < ApplicationController
  before_action :set_matricula, only: [:show, :edit, :update, :destroy]

  # GET /matriculas
  # GET /matriculas.json
  def index
    @matriculas = Matricula.all.order("codigo ASC")
  end

  # GET /matriculas/1
  # GET /matriculas/1.json
  def show
  end

  # GET /matriculas/new
  def new
    @matricula = Matricula.new
  end

  # GET /matriculas/1/edit
  def edit
  end

  # POST /matriculas
  # POST /matriculas.json
  def create
    @matricula = Matricula.new(matricula_params)

    respond_to do |format|
      if @matricula.save
        format.html { redirect_to @matricula, notice: 'Matricula was successfully created.' }
        format.json { render :show, status: :created, location: @matricula }
      else
        format.html { render :new }
        format.json { render json: @matricula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matriculas/1
  # PATCH/PUT /matriculas/1.json
  def update
    respond_to do |format|
      if @matricula.update(matricula_params)
        format.html { redirect_to @matricula, notice: 'Matricula was successfully updated.' }
        format.json { render :show, status: :ok, location: @matricula }
      else
        format.html { render :edit }
        format.json { render json: @matricula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matriculas/1
  # DELETE /matriculas/1.json
  def destroy
    @matricula.destroy
    respond_to do |format|
      format.html { redirect_to matriculas_url, notice: 'Matricula was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @matricula = Matricula.where(codigo: params[:codigo]).first
    respond_to do |format|
      format.json do
        if @matricula.present?
          render json: @matricula
        else
          head :not_found
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_matricula
      @matricula = Matricula.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def matricula_params
      params.require(:matricula).permit(:codigo, :empresa_id)
    end
end

app/views/matriculas/_form.html.erb
<%= form_for(@matricula, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @matricula.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@matricula.errors.count, "error") %> prohibited this matricula from being saved:</h4>

      <ul>
      <% @matricula.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :codigo, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :codigo, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :empresa_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :empresa_id, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/matriculas/edit.html.erb
<div class="page-header">
  <%= link_to matriculas_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @matricula, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing matricula</h1>
</div>

<%= render 'form' %>

app/views/matriculas/index.html.erb
<div class="page-header">
  <%= link_to new_matricula_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Agregar Matricula
  <% end %>
  <h3>Matriculas</h3>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Codigo</th>
        <th>Empresa</th>
       
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @matriculas) do |matricula| %>
        <td><%= matricula.codigo %></td>
        <td><%= matricula.get_nombre_empresa %></td>       
          
      <% end %>
    </tbody>
  </table>
</div>

app/views/matriculas/new.html.erb
<div class="page-header">
  <%= link_to matriculas_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New matricula</h1>
</div>

<%= render 'form' %>

app/views/matriculas/show.html.erb
<div class="page-header">
  <%= link_to matriculas_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_matricula_path(@matricula), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show matricula</h1>
</div>

<dl class="dl-horizontal">
  <dt>Codigo:</dt>
  <dd><%= @matricula.codigo %></dd>

  <dt>Empresa:</dt>
  <dd><%= @matricula.empresa_id %></dd>

</dl>