config/routes.rb
Rails.application.routes.draw do
  resources :empresa_choferes do
    get :search, on: :collection
  end
  resources :matriculas do
    get :search, on: :collection
  end
  resources :choferes
  resources :empresas
  resources :vehiculos
  resources :matriculas_log
  resources :tarifas
  resources :liquidacion_de_viajes do
    get :last, on: :collection
  end

  root to: 'liquidacion_de_viajes#index'
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  self.table_name = 'empresas'
  self.inheritance_column = 'ruby_type'
  self.primary_key = 'id'

  if ActiveRecord::VERSION::STRING < '4.0.0' || defined?(ProtectedAttributes)
    attr_accessible :razon_social, :direccion, :telefonos, :contacto, :fecha_ingreso, :bps_numero, :bps_digito, :pat_socio, :rubros, :estados_id, :porc_comision
  end

  has_many :choferes, :foreign_key => 'empresas_id', :class_name => 'Chofer'
  has_many :matriculas, :foreign_key => 'empresa_id', :class_name => 'Matricula'
  has_many :matriculas_logs, :foreign_key => 'empresa_id', :class_name => 'MatriculasLog'
  has_many :tramites, :foreign_key => 'empresas_id', :class_name => 'Tramite'
  has_many :licencias, :foreign_key => 'id_empresa', :class_name => 'Licencia'
  has_many :vehiculos, :foreign_key => 'empresas_id', :class_name => 'Vehiculo'
  has_many :matriculas_by_matriculas_log, :source => :matricula, :through => :matriculas_logs, :foreign_key => 'matricula_id', :class_name => 'Matricula'
  has_many :vehiculos_by_matriculas_log, :source => :vehiculo, :through => :matriculas_logs, :foreign_key => 'vehiculo_id', :class_name => 'Vehiculo'
  has_many :gestorias, :through => :tramites, :foreign_key => 'gestorias_id', :class_name => 'Gestoria'
  has_many :liquidacion_de_viajes, :foreign_key => 'id_empresa', :class_name => 'LiquidacionDeViajes'
  has_many :empresa_choferes, :foreign_key => 'id_empresa', :class_name => 'EmpresaChoferes'


  def get_estado
    if self.estados_id == 1
      return "Activa"
    else
      return "Inactiva"
    end
  end

  def get_choferes
    EmpresaChofer.where('id_empresa = ?', self.id)
  end

  def get_choferes_activos
    EmpresaChofer.where('id_empresa = ?', self.id).where('estado = ?', 1)
  end

end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]

  # GET /empresas
  # GET /empresas.json
  def index
    if params[:estado]      
      @estado = params[:estado].to_i       
      @empresas = Empresa.where('estados_id = ?', @estado).order("razon_social ASC")
    end
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show       
    @empresa_choferes = Empresa.find(params[:id]).get_choferes_activos    
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
  end

  # GET /empresas/1/edit
  def edit
    @estado = Empresa.find(params[:id]).estados_id
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Se ha creado el registro de la empresa.' }
        format.json { render :show, status: :created, location: @empresa }
      else
        format.html { render :new }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to @empresa, notice: 'Se ha actualizado el registro de la empresa.' }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresas_url, notice: 'Empresa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params.require(:empresa).permit(:razon_social, :direccion, :telefonos, :contacto, :fecha_ingreso, :bps_numero, :bps_digito, :pat_socio, :rubros, :estados_id)
    end
end

app/views/empresas/_form.html.erb
<%= form_for(@empresa, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @empresa.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@empresa.errors.count, "error") %> prohibited this empresa from being saved:</h4>

      <ul>
      <% @empresa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :razon_social, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :razon_social, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :direccion, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :direccion, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :telefonos, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :telefonos, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :contacto, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :contacto, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fecha_ingreso, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :fecha_ingreso, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :bps_numero, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :bps_numero, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :bps_digito, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :bps_digito, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :pat_socio, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :pat_socio, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :rubros, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :rubros, :class => "form-control" %>
    </div>
  </div> 

  <div class="form-group">
    <%= f.label :Estado, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select(:estados_id, options_for_select([['Activa', 1], ['Inactiva', 2]], :selected =>  @estado)) %>
    </div>
  </div> 

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Confirmar", :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<div class="page-header">
  <%= link_to empresas_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Atras
  <% end %>
  <%= link_to @empresa, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Ver
  <% end %>
  <h1>Empresa</h1>
</div>

<%= render 'form' %>

app/views/empresas/index.html.erb
<div class="page-header">
  <%= link_to new_empresa_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Agregar Empresa
  <% end %>
  <h1>Empresas</h1>
</div>

<%= form_tag empresas_path, :method => 'get', id: "search-form" do %>
 <div class="field"> 

 <%= label_tag "Estado:  " %>  
 <%= select_tag(:estado, options_for_select([
  ['Activas', 1], ['Inactivas', 2] 
  ], selected: @estado )) %> 

  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   

  <%= submit_tag "Aplicar seleccion" %>
  <br><br>
</div>
<% end %>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Razon social</th>                                               
        <th><div align="center">Bps</th>          
        <th>Rubros</th>           
        <th></th>
        <th></th>       
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @empresas) do |empresa| %>
        <td><%= empresa.razon_social %></td>                                              
        <td><div align="center"><%= empresa.bps_digito %></td>          
        <td><%= empresa.rubros %></td>        
        <td><%= link_to 'Ver', empresa %></td>
        <td><%= link_to 'Editar', edit_empresa_path(empresa) %></td>             
      <% end %>
    </tbody>
  </table>
</div>

app/views/empresas/new.html.erb
<div class="page-header">
  <%= link_to empresas_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Atras
  <% end %>
  <h1>Nueva empresa</h1>
</div>

<%= render 'form' %>

app/views/empresas/show.html.erb
<div class="page-header">
  <%= link_to empresas_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Atras
  <% end %>
  <%= link_to edit_empresa_path(@empresa), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h3><%= @empresa.razon_social %></h3>
</div>

<dl class="dl-horizontal"> 

  <dt>Direccion:</dt>
  <dd><%= @empresa.direccion %></dd>

  <dt>Telefonos:</dt>
  <dd><%= @empresa.telefonos %></dd>

  <dt>Contacto:</dt>
  <dd><%= @empresa.contacto %></dd>

  <dt>Fecha ingreso:</dt>
  <dd><%= @empresa.fecha_ingreso.strftime("%d/%m/%Y") %></dd>

  <dt>Numero BPS:</dt>
  <dd><%= @empresa.bps_numero %></dd>

  <dt>Digito BPS:</dt>
  <dd><%= @empresa.bps_digito %></dd>

  <dt>Socio Patronal:</dt>
  <dd><%= @empresa.pat_socio %></dd>

  <dt>Rubros:</dt>
  <dd><%= @empresa.rubros %></dd>

  <dt>Estado:</dt>
  <dd><%= @empresa.get_estado %></dd>

</dl>

<h4>Choferes</h4>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>       
        <th>Nombre</th>       
        <th>Fecha alta</th>
        <th>Fecha baja</th>        
        <th>Fecha alta bps</th>       
        <th>Porc comision</th>             
        <th></th>
        <th></th>      
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @empresa_choferes) do |empresa_chofer| %>              
        <td><%= empresa_chofer.get_nombre_chofer %></td>      
        <td><%= empresa_chofer.get_fecha_alta_editada %></td>
        <td><%= empresa_chofer.get_fecha_baja_editada %></td>                                 
        <td><%= empresa_chofer.get_fecha_alta_bps_editada %></td>            
        <td><%= empresa_chofer.porc_comision %></td>                    
        <td><%= link_to 'Ver', empresa_chofer %></td>
        <td><%= link_to 'Editar', edit_empresa_chofer_path(empresa_chofer, :id_empresa => @empresa.id) %></td>           
      <% end %>
    </tbody>
  </table>
</div>